// STRATEGIC PARTNERSHIP — 60 authored Ryan ❤️ Indra easter eggs.
// Most are rare: gated by real data conditions and/or a deterministic
// once-per-day lottery (c.dailyRandom), so they surface occasionally and
// unexpectedly. Any number shown is computed from Indra's data.
import { def, plural, num, fmtDayShort, daysBetween, isWeekend, weekdayOf, type Ctx } from '../h';
import type { InsightDef } from '../types';

const C = 'partnership' as const;
/** deterministic per-day lottery: true on roughly `p` of days */
const lucky = (c: Ctx, id: string, p: number) => c.dailyRandom(id) < p;
const todayIs = (c: Ctx, mmdd: string) => c.todayKey.slice(5) === mmdd;
const dom = (c: Ctx) => Number(c.todayKey.slice(8));
const firstToday = (c: Ctx) => c.dayMap.get(c.todayKey)?.events[0] ?? null;

export const partnershipInsights: InsightDef[] = [
  def({ id: 'rp-founders-note', title: "Founder's Note", category: C, rarity: 'uncommon', priority: 88, when: (c) => c.n >= 1 && c.n <= 3, msg: () => `Founder's Note: Ryan built this entire, absurdly over-engineered Operations Center for you. It is the most romantic stupid thing he has ever done, and he regrets nothing.` }),
  def({ id: 'rp-commitment', title: 'Commitment', category: C, rarity: 'uncommon', priority: 70, minEvents: 20, when: (c) => lucky(c, 'rp-commitment', 0.15), msg: (c) => `Ryan has now loved you through ${num(c.n)} documented bowel movements. His resolve remains absolute.` }),
  def({ id: 'rp-relationship-infrastructure', title: 'Relationship Infrastructure', category: C, rarity: 'uncommon', priority: 68, when: (c) => c.todayCount > 0 && lucky(c, 'rp-infra', 0.12), msg: () => `Whatever today brings, you successfully pooped and Ryan still thinks you're cute.` }),
  def({ id: 'rp-independent-verification', title: 'Independent Verification', category: C, rarity: 'uncommon', priority: 66, minEvents: 5, when: (c) => c.todayCount > 0 && lucky(c, 'rp-verify', 0.1), msg: () => `Data unavailable on whether Ryan is proud of this specific poop. Historical evidence suggests yes.` }),
  def({ id: 'rp-long-term-outlook', title: 'Long-Term Outlook', category: C, rarity: 'uncommon', priority: 72, when: (c) => c.completeMonths.length >= 1 && dom(c) <= 3, msg: () => `Another month of data. Ryan remains bullish on Indra.` }),
  def({ id: 'rp-core-metric', title: 'Core Metric', category: C, rarity: 'rare', priority: 70, minEvents: 30, when: (c) => lucky(c, 'rp-core', 0.1), msg: () => `Poop statistics come and go. Ryan thinking you're adorable appears remarkably stable.` }),
  def({ id: 'rp-strategic-partnership', title: 'Strategic Partnership', category: C, priority: 60, minEvents: 3, when: (c) => lucky(c, 'rp-strat', 0.2), msg: () => `Indra handles outbound logistics. Ryan provides emotional infrastructure.` }),
  def({ id: 'rp-analyst-note', title: 'Analyst Note', category: C, rarity: 'rare', priority: 72, minEvents: 40, when: (c) => lucky(c, 'rp-analyst', 0.1), msg: () => `No correlation has been detected between poop frequency and how much Ryan loves you. He appears to have maxed out the scale.` }),
  def({ id: 'rp-peer-review', title: 'Peer Review', category: C, rarity: 'uncommon', priority: 66, when: (c) => c.poopDays >= 10 && lucky(c, 'rp-peer', 0.1), msg: () => `Ryan has reviewed the findings and concluded that Indra remains extremely cute.` }),
  def({ id: 'rp-investor-guidance', title: 'Investor Guidance', category: C, rarity: 'uncommon', priority: 66, minDays: 30, when: (c) => lucky(c, 'rp-investor', 0.1), msg: () => `Analysts continue to recommend holding Indra indefinitely.` }),
  def({ id: 'rp-system-dependency', title: 'System Dependency', category: C, rarity: 'rare', priority: 66, minEvents: 15, when: (c) => lucky(c, 'rp-dep', 0.08), msg: () => `Bowel Operations can technically function without Ryan. Indra Operations are considerably more fun with him.` }),
  def({ id: 'rp-valentines', title: "Valentine's Memo", category: C, rarity: 'legendary', priority: 99, when: (c) => todayIs(c, '02-14'), msg: () => `Happy Valentine's Day from Ryan. He loves you completely, regardless of today's operational status.` }),
  def({ id: 'rp-streak-briefing', title: 'Streak Briefing Delivered', category: C, rarity: 'uncommon', priority: 70, when: (c) => c.currentStreak >= 5 && lucky(c, 'rp-streak', 0.3), msg: (c) => `Ryan has been briefed on the ${c.currentStreak}-day streak. His official response: "so proud, and slightly confused about why I know this."` }),
  def({ id: 'rp-no-delays', title: 'Love Is Not Subject to Delays', category: C, rarity: 'uncommon', priority: 78, when: (c) => c.todayCount === 0 && c.openGap >= 2, msg: () => `During this supply chain disruption, please know that Ryan's love is not subject to delays, backorders, or shipping fees.` }),
  def({ id: 'rp-max-already', title: 'Already at Maximum', category: C, rarity: 'rare', priority: 80, when: (c) => c.todayCount >= 3, msg: (c) => `${c.todayCount} movements today. Ryan would like it noted that he does not love you ${c.todayCount} times as much today, because he was already at the maximum.` }),
  def({ id: 'rp-late-night', title: 'After-Hours Memo', category: C, rarity: 'uncommon', priority: 74, when: (c) => { const l = c.dayMap.get(c.todayKey)?.events; return !!l && (l[l.length - 1].hour >= 22 || l[l.length - 1].hour < 3); }, msg: () => `Late-night operations noted. Ryan hopes you get some sleep soon, cutie.` }),
  def({ id: 'rp-early-riser', title: 'Early Riser Memo', category: C, rarity: 'uncommon', priority: 72, when: (c) => { const f = firstToday(c); return !!f && f.hour >= 4 && f.hour < 7; }, msg: () => `Up early and already productive. Ryan is impressed and, statistically, probably still asleep.` }),
  def({ id: 'rp-weekend-plan', title: 'Weekend Recommendation', category: C, rarity: 'uncommon', priority: 62, when: (c) => isWeekend(weekdayOf(c.todayKey)) && c.todayCount > 0 && lucky(c, 'rp-weekend', 0.2), msg: () => `Weekend deployment confirmed. Ryan suggests celebrating with snacks and a cuddle. Management approves the budget.` }),
  def({ id: 'rp-monday', title: 'Monday Commendation', category: C, rarity: 'uncommon', priority: 62, when: (c) => weekdayOf(c.todayKey) === 1 && c.todayCount > 0 && lucky(c, 'rp-monday', 0.2), msg: () => `Monday: handled. Ryan thinks you're amazing at Mondays, and also at everything else.` }),
  def({ id: 'rp-hundred', title: 'One Hundred, With Love', category: C, rarity: 'rare', priority: 90, minEvents: 100, when: (c) => c.n >= 100 && c.n < 110, msg: () => `One hundred movements, and Ryan has loved you through every single one. He'd like the record to show he'd happily love you through a hundred thousand.` }),
  def({ id: 'rp-silly-things', title: 'Not a Poop Fact', category: C, rarity: 'legendary', priority: 85, minEvents: 10, when: (c) => lucky(c, 'rp-silly', 0.03), msg: () => `Not a poop fact: Ryan is really, genuinely glad he gets to be the person who builds you silly things.` }),
  def({ id: 'rp-off-the-record', title: 'Off the Record', category: C, rarity: 'legendary', priority: 85, minDays: 14, when: (c) => lucky(c, 'rp-offrecord', 0.03), msg: () => `Off the record: you make ordinary days better. Ryan asked the Intelligence Division to tell you that, and it agreed immediately.` }),
  def({ id: 'rp-favorite-thing', title: 'Beyond Measurement', category: C, rarity: 'legendary', priority: 85, when: (c) => c.poopDays >= 20 && lucky(c, 'rp-fav', 0.03), msg: () => `The Intelligence Division is not qualified to measure this, but Ryan says being with you is his favorite thing in the world.` }),
  def({ id: 'rp-every-day', title: 'Full Dataset Review', category: C, rarity: 'legendary', priority: 86, minEvents: 50, when: (c) => lucky(c, 'rp-everyday', 0.03), msg: (c) => `A full review of all ${plural(c.trackedDays, 'day')} in the dataset found zero days on which Ryan didn't love you. The review was very thorough.` }),
  def({ id: 'rp-shareholder-letter', title: 'Quarterly Shareholder Letter', category: C, rarity: 'rare', priority: 80, minDays: 30, when: (c) => [0, 3, 6, 9].includes(c.now.getMonth()) && dom(c) <= 3, msg: () => `Dear Indra, the partnership continues to outperform every forecast. Love, Ryan (sole shareholder, not selling).` }),
  def({ id: 'rp-annual', title: 'Annual Report: Personal Edition', category: C, rarity: 'legendary', priority: 98, when: (c) => !!c.firstKey && daysBetween(c.firstKey, c.todayKey) === 365, msg: () => `One year of the Bowel Operations Center. Ryan remains, as ever, your biggest fan and most unnecessary software engineer.` }),
  def({ id: 'rp-hr-complaint', title: 'HR Complaint Dismissed', category: C, rarity: 'rare', priority: 64, minEvents: 25, when: (c) => lucky(c, 'rp-hr', 0.07), msg: () => `HR has received a complaint that Ryan talks about how cute Indra is too much. The complaint has been dismissed for lack of merit.` }),
  def({ id: 'rp-performance-review', title: 'Performance Review', category: C, rarity: 'uncommon', priority: 70, when: (c) => c.completeMonths.length >= 1 && dom(c) >= 4 && dom(c) <= 6, msg: () => `Monthly Performance Review: Exceeds Expectations. Reviewer: Ryan. Reviewer bias: extreme, and fully disclosed.` }),
  def({ id: 'rp-consultant', title: 'Consultant Findings', category: C, rarity: 'rare', priority: 64, minEvents: 12, when: (c) => lucky(c, 'rp-consult', 0.06), msg: () => `An outside consultant was hired to find a single flaw in Indra. The consultant has been let go. Ryan was the consultant.` }),
  def({ id: 'rp-forecast', title: 'Emotional Weather Forecast', category: C, rarity: 'rare', priority: 60, minEvents: 8, when: (c) => lucky(c, 'rp-weather', 0.05), msg: () => `Today's forecast: 100% chance Ryan thinks you're cute, with scattered cuddles developing throughout the evening.` }),
  def({ id: 'rp-sla', title: 'Service Level Agreement', category: C, rarity: 'rare', priority: 64, when: (c) => c.currentStreak >= 3 && lucky(c, 'rp-sla', 0.1), msg: () => `Service Level Agreement: Ryan guarantees 99.999% uptime on loving you. The remaining 0.001% is when you steal the blanket.` }),
  def({ id: 'rp-merger', title: 'Merger Update', category: C, rarity: 'rare', priority: 62, minEvents: 60, when: (c) => lucky(c, 'rp-merger', 0.05), msg: () => `Merger talks between Indra and Ryan remain extremely friendly. Regulators have no objections. Nobody asked the regulators.` }),
  def({ id: 'rp-board-meeting', title: 'Sunday Board Meeting', category: C, rarity: 'uncommon', priority: 62, minEvents: 5, when: (c) => weekdayOf(c.todayKey) === 0 && lucky(c, 'rp-board', 0.15), msg: () => `The Sunday board meeting has concluded. Agenda item one: Indra is great. The motion carried unanimously, 1–0.` }),
  def({ id: 'rp-customer-support', title: 'Customer Support Note', category: C, rarity: 'uncommon', priority: 66, when: (c) => c.todayCount === 0 && c.openGap >= 1 && lucky(c, 'rp-support', 0.3), msg: () => `While operations are on standby, Ryan's department is available 24/7 for hugs, tea, and moral support. No ticket required.` }),
  def({ id: 'rp-benchmark', title: 'Benchmark Results', category: C, rarity: 'rare', priority: 64, minEvents: 35, when: (c) => lucky(c, 'rp-bench', 0.06), msg: () => `Indra was benchmarked against every other person Ryan has ever met. Indra won. It wasn't close.` }),
  def({ id: 'rp-kpi', title: "Ryan's KPI", category: C, rarity: 'rare', priority: 60, when: (c) => c.poopDays >= 15 && lucky(c, 'rp-kpi', 0.06), msg: () => `Ryan's only key performance indicator for this app: the number of times you laughed at it. Current status: hopefully a lot.` }),
  def({ id: 'rp-throughput-of-thought', title: 'Competing Throughput', category: C, rarity: 'rare', priority: 62, when: (c) => c.multiDayCount >= 3 && lucky(c, 'rp-thru', 0.1), msg: (c) => `${c.multiDayCount} high-throughput days on record. Impressive. Ryan's daily throughput of thinking about you remains higher.` }),
  def({ id: 'rp-root-cause', title: 'Root Cause Analysis', category: C, rarity: 'rare', priority: 62, minEvents: 18, when: (c) => lucky(c, 'rp-rca', 0.05), msg: () => `Root cause analysis for why this app exists: Ryan loves you and has a completely normal amount of free time.` }),
  def({ id: 'rp-changelog', title: 'Changelog', category: C, rarity: 'rare', priority: 60, minEvents: 22, when: (c) => lucky(c, 'rp-changelog', 0.05), msg: () => `Changelog v1.0 — Added: 500 insights, 30 achievements, confetti. Fixed: nothing about Indra, because she was already perfect.` }),
  def({ id: 'rp-terms', title: 'Terms of Service, Section 4', category: C, rarity: 'rare', priority: 58, minEvents: 28, when: (c) => lucky(c, 'rp-terms', 0.05), msg: () => `Terms of Service, Section 4: Ryan reserves the right to think you're adorable at any time, without prior notice.` }),
  def({ id: 'rp-uptime', title: 'Relationship Uptime', category: C, rarity: 'rare', priority: 62, minDays: 60, when: (c) => lucky(c, 'rp-uptime', 0.05), msg: (c) => `Relationship uptime since the Center opened ${plural(c.trackedDays, 'day')} ago: 100%. Incidents reported: zero. Naps taken together: numerous.` }),
  def({ id: 'rp-bug-report', title: 'Bug Report: Won’t Fix', category: C, rarity: 'rare', priority: 60, minEvents: 33, when: (c) => lucky(c, 'rp-bug', 0.05), msg: () => `Bug report filed: "Indra too cute, causes Ryan to stare." Status: Won't fix. Working as intended.` }),
  def({ id: 'rp-roadmap', title: 'Product Roadmap', category: C, rarity: 'rare', priority: 58, minDays: 45, when: (c) => lucky(c, 'rp-roadmap', 0.05), msg: () => `Product roadmap: more insights, more achievements, and Ryan loving you even more (roadmap item may already be at maximum capacity).` }),
  def({ id: 'rp-disclosure', title: 'Required Disclosure', category: C, rarity: 'rare', priority: 58, minEvents: 45, when: (c) => lucky(c, 'rp-disclose', 0.05), msg: () => `Disclosure: Ryan holds a significant long position in Indra. He is not required to disclose this. He just wanted to.` }),
  def({ id: 'rp-press-release', title: 'Press Release', category: C, rarity: 'rare', priority: 60, minEvents: 50, when: (c) => lucky(c, 'rp-press', 0.05), msg: () => `FOR IMMEDIATE RELEASE: Local man still extremely into his girlfriend. More at eleven.` }),
  def({ id: 'rp-tech-support', title: 'Tech Support', category: C, rarity: 'rare', priority: 56, minEvents: 6, when: (c) => lucky(c, 'rp-techsupport', 0.05), msg: () => `Have you tried turning it off and on again? Ryan has. It did not change how much he loves you.` }),
  def({ id: 'rp-morning-memo', title: 'Morning Memo', category: C, rarity: 'uncommon', priority: 64, when: (c) => { const f = firstToday(c); return !!f && f.hour >= 6 && f.hour < 10 && lucky(c, 'rp-morning', 0.15); }, msg: () => `Morning operations complete. Ryan recommends coffee, a good breakfast, and remembering that you're loved.` }),
  def({ id: 'rp-welcome-back', title: 'Welcome Back', category: C, rarity: 'uncommon', priority: 84, when: (c) => c.gaps.some((g) => g.toKey === c.todayKey && g.len >= 2), msg: () => `Welcome back to full operations. Ryan never doubted you for a second.` }),
  def({ id: 'rp-evening-wind-down', title: 'End-of-Day Memo', category: C, rarity: 'uncommon', priority: 60, when: (c) => c.now.getHours() >= 21 && c.todayCount > 0 && lucky(c, 'rp-evening', 0.3), msg: () => `Today's operations are complete. Ryan hopes you have a cozy evening, you magnificent logistics professional.` }),
  def({ id: 'rp-plaque', title: 'Commemorative Plaque', category: C, rarity: 'rare', priority: 82, when: (c) => c.currentStreak >= 5 && c.currentStreak === c.longestStreak && lucky(c, 'rp-plaque', 0.5), msg: (c) => `Ryan has requested that this ${c.currentStreak}-day record streak be commemorated with a small plaque. The plaque will read: "Indra — very good at things."` }),
  def({ id: 'rp-hidden-message', title: 'Hidden Message', category: C, rarity: 'legendary', priority: 95, minEvents: 5, when: (c) => lucky(c, 'rp-hidden', 0.01), msg: () => `If you're reading this, Ryan loves you. That's it. That's the whole insight.` }),
  def({ id: 'rp-lucky-days', title: 'Lucky Days Ledger', category: C, rarity: 'rare', priority: 76, minEvents: 75, when: (c) => lucky(c, 'rp-luckydays', 0.04), msg: (c) => `Across ${plural(c.trackedDays, 'day')} of operations, the number of days Ryan felt lucky to be with you: ${num(c.trackedDays)}. Perfect correlation.` }),
  def({ id: 'rp-day-one', title: 'Confirmed Since Day One', category: C, rarity: 'rare', priority: 70, when: (c) => c.completeMonths.length >= 3 && lucky(c, 'rp-dayone', 0.1), msg: (c) => `${c.completeMonths.length} full months of data now confirm what Ryan knew on day one: you're the best.` }),
  def({ id: 'rp-exec-summary', title: 'Executive Summary', category: C, rarity: 'uncommon', priority: 62, minEvents: 14, when: (c) => lucky(c, 'rp-execsum', 0.06), msg: () => `Executive Summary: Indra pooped. Indra is great. Ryan loves Indra. End of summary.` }),
  def({ id: 'rp-audit', title: 'Independent Audit', category: C, rarity: 'rare', priority: 64, minDays: 90, when: (c) => lucky(c, 'rp-audit', 0.05), msg: () => `An independent audit of the relationship found zero irregularities, one extremely cute girlfriend, and one boyfriend who built an app about poop.` }),
  def({ id: 'rp-contingency', title: 'Contingency Plan', category: C, rarity: 'uncommon', priority: 76, when: (c) => c.todayCount === 0 && c.openGap >= 3, msg: () => `Contingency plan activated: Ryan is standing by with water, snacks, and unconditional love. Mostly the love.` }),
  def({ id: 'rp-halloween', title: 'Halloween Memo', category: C, rarity: 'legendary', priority: 97, when: (c) => todayIs(c, '10-31'), msg: () => `Happy Halloween from Ryan. You are the least scary and most adorable entry in this entire database.` }),
  def({ id: 'rp-christmas', title: 'Christmas Memo', category: C, rarity: 'legendary', priority: 97, when: (c) => todayIs(c, '12-25'), msg: () => `Merry Christmas from Ryan. All he wanted for Christmas was you (and for this app to compile on the first try).` }),
  def({ id: 'rp-new-year', title: "New Year's Resolution", category: C, rarity: 'legendary', priority: 97, when: (c) => todayIs(c, '01-01'), msg: () => `Happy New Year! Ryan's resolution: keep loving you exactly this much. It's the only resolution he's fully confident about.` }),
  def({ id: 'rp-doing-great', title: 'Friendly Reminder', category: C, rarity: 'rare', priority: 58, minEvents: 4, when: (c) => lucky(c, 'rp-great', 0.04), msg: () => `Friendly reminder from Ryan's department: you're doing great. Today, and in general.` }),
  def({ id: 'rp-first-movement-memory', title: 'Where It All Began', category: C, rarity: 'rare', priority: 66, minDays: 30, when: (c) => !!c.firstKey && lucky(c, 'rp-began', 0.05), msg: (c) => `The Center opened on ${fmtDayShort(c.firstKey!)}. Ryan's feelings for you predate the Center considerably, and have outgrown it.` }),
];
